// src/data.js

export const categories = [
  { id: 'all', name: 'All Drops' },
    { id: 'retro', name: 'Retro Kits' },
      { id: 'basketball', name: 'NBA Swingman' },
        { id: 'collar', name: 'Streetwear Collar' },
          { id: 'ferrari', name: 'Ferrari Special' },
          ];

          export const products = [
            // --- HERO ITEM (The "Hot Deal") ---
              {
                  id: 1,
                      name: 'Argentina Messi #10 (World Cup Ed.)',
                          price: 349,
                              category: 'retro',
                                  image: 'https://i.ibb.co/1fhSty2p/1000370961-removebg-preview.png', // The Blue/White Stripes Jersey
                                      isHot: true, 
                                        },

                                          // --- FERRARI ---
                                            {
                                                id: 2,
                                                    name: 'Scuderia Ferrari Racing Tee',
                                                        price: 349,
                                                            category: 'ferrari',
                                                                image: 'https://i.ibb.co/99t1LpGS/1000371094-removebg-preview.png', // The White Ferrari T-Shirt
                                                                    isHot: false,
                                                                      },

                                                                        // --- RETRO KITS (Price 349) ---
                                                                          {
                                                                              id: 3,
                                                                                  name: 'Inter Milan Figo #7',
                                                                                      price: 349,
                                                                                          category: 'retro',
                                                                                              image: 'https://i.ibb.co/KpkRyVK8/1000371159-removebg-preview.png', // Blue/Black Stripes
                                                                                                  isHot: false,
                                                                                                    },
                                                                                                      {
                                                                                                          id: 4,
                                                                                                              name: 'France Retro Zidane #10',
                                                                                                                  price: 349,
                                                                                                                      category: 'retro',
                                                                                                                          image: 'https://i.ibb.co/cSvvk5tj/1000370965-removebg-preview.png', // Blue Jersey with Collar
                                                                                                                              isHot: false,
                                                                                                                                },
                                                                                                                                  {
                                                                                                                                      id: 5,
                                                                                                                                          name: 'Italia Maldini #3',
                                                                                                                                              price: 349,
                                                                                                                                                  category: 'retro',
                                                                                                                                                      image: 'https://i.ibb.co/hJJmpcdw/1000371170-removebg-preview.png', // Dark Blue Italy Kit
                                                                                                                                                          isHot: false,
                                                                                                                                                            },
                                                                                                                                                              {
                                                                                                                                                                  id: 6,
                                                                                                                                                                      name: 'Neymar Jr #10 (Santos/Black)',
                                                                                                                                                                          price: 349,
                                                                                                                                                                              category: 'retro',
                                                                                                                                                                                  image: 'https://i.ibb.co/cSfmwbnT/1000370969-removebg-preview.png', // The Black Pinstripe Jersey
                                                                                                                                                                                      isHot: false,
                                                                                                                                                                                        },

                                                                                                                                                                                          // --- BASKETBALL / NBA (Price 249) ---
                                                                                                                                                                                            {
                                                                                                                                                                                                id: 7,
                                                                                                                                                                                                    name: 'Boston Celtics Brown #7',
                                                                                                                                                                                                        price: 249,
                                                                                                                                                                                                            category: 'basketball',
                                                                                                                                                                                                                image: 'https://i.ibb.co/SwzCnBkj/1000371139-removebg-preview.png', // White Celtics Jersey
                                                                                                                                                                                                                    isHot: false,
                                                                                                                                                                                                                      },
                                                                                                                                                                                                                        {
                                                                                                                                                                                                                            id: 8,
                                                                                                                                                                                                                                name: 'Dallas Mavericks Kidd #5',
                                                                                                                                                                                                                                    price: 249,
                                                                                                                                                                                                                                        category: 'basketball',
                                                                                                                                                                                                                                            image: 'https://i.ibb.co/SDF04pHy/1000371153-removebg-preview.png', // Blue Dallas Jersey
                                                                                                                                                                                                                                                isHot: false,
                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                        id: 9,
                                                                                                                                                                                                                                                            name: 'Miami Heat Wade #3',
                                                                                                                                                                                                                                                                price: 249,
                                                                                                                                                                                                                                                                    category: 'basketball',
                                                                                                                                                                                                                                                                        image: 'https://i.ibb.co/9Hyzdp54/1000371157-removebg-preview.png', // Black Miami Jersey
                                                                                                                                                                                                                                                                            isHot: false,
                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                    id: 10,
                                                                                                                                                                                                                                                                                        name: 'Lakers Kobe Bryant #8',
                                                                                                                                                                                                                                                                                            price: 249,
                                                                                                                                                                                                                                                                                                category: 'basketball',
                                                                                                                                                                                                                                                                                                    image: 'https://i.ibb.co/vvCx3Bqv/1000371155-removebg-preview.png', // Yellow Lakers Jersey
                                                                                                                                                                                                                                                                                                        isHot: false,
                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                id: 11,
                                                                                                                                                                                                                                                                                                                    name: 'Orlando Magic O\'Neal #32',
                                                                                                                                                                                                                                                                                                                        price: 249,
                                                                                                                                                                                                                                                                                                                            category: 'basketball',
                                                                                                                                                                                                                                                                                                                                image: 'https://i.ibb.co/dJDLHn5d/1000371161-removebg-preview.png', // White Pinstripe Magic Jersey
                                                                                                                                                                                                                                                                                                                                    isHot: false,
                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                            id: 13,
                                                                                                                                                                                                                                                                                                                                                name: 'NY Knicks Retro #1',
                                                                                                                                                                                                                                                                                                                                                    price: 249,
                                                                                                                                                                                                                                                                                                                                                        category: 'basketball',
                                                                                                                                                                                                                                                                                                                                                            image: 'https://i.ibb.co/KpkRyVK8/1000371159-removebg-preview.png', // White/Orange/Blue Trim
                                                                                                                                                                                                                                                                                                                                                                isHot: false,
                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                    // --- STREETWEAR / COLLAR (Price 349) ---
                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                          id: 14,
                                                                                                                                                                                                                                                                                                                                                                              name: 'Saint Black Zip Edition',
                                                                                                                                                                                                                                                                                                                                                                                  price: 349,
                                                                                                                                                                                                                                                                                                                                                                                      category: 'collar',
                                                                                                                                                                                                                                                                                                                                                                                          image: 'https://i.ibb.co/S4bNLysS/1000371125-removebg-preview.png', // Black shirt with Pink 00 text
                                                                                                                                                                                                                                                                                                                                                                                              isHot: false,
                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                      id: 15,
                                                                                                                                                                                                                                                                                                                                                                                                          name: 'YourBrand Sports White',
                                                                                                                                                                                                                                                                                                                                                                                                              price: 349,
                                                                                                                                                                                                                                                                                                                                                                                                                  category: 'collar',
                                                                                                                                                                                                                                                                                                                                                                                                                      image: 'https://i.ibb.co/VcyQS3hs/1000371137-removebg-preview.png', // White shirt with Red/Yellow Logo
                                                                                                                                                                                                                                                                                                                                                                                                                          isHot: false,
                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                  id: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                      name: 'Brand State Sports Div',
                                                                                                                                                                                                                                                                                                                                                                                                                                          price: 349,
                                                                                                                                                                                                                                                                                                                                                                                                                                              category: 'collar',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  image: 'https://i.ibb.co/LhQtQwZk/1000371135-removebg-preview.png', // White/Blue Text "Brand State"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      isHot: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: 17,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name: 'Juventus Style Stripe',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      price: 349,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          category: 'collar',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              image: 'https://i.ibb.co/VW3fzn0h/1000371133-removebg-preview.png', // Black/White Vertical Stripes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isHot: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    